### ISSUE TITLE
read yaml, modify it, and write it back out again

### ISSUE THREAD

**Issue by devoncarew** [Andersmholmgren/yamlicious#2]
Just checking - does this library support the use case of parsing a yaml file, making some changes to the parsed info, and writing that file back out? I'd like to be able to change targeted sections of a yaml file without affecting other sections of the file. Thanks!

**Comment by Andersmholmgren** [comment]
No, it treats yaml as just another serialisation format like json, xml etc. It reads and writes it in its entirety.
